FROM node:16-alpine

WORKDIR /app

# Copie o package.json e instale as dependências
COPY package.json .
RUN npm install

# Copie o código do seu frontend
COPY . .

# Exponha a porta utilizada pelo frontend
EXPOSE 80

# Comando para iniciar sua aplicação frontend (substitua pelo seu comando real)
CMD ["npm", "start"]  # Substitua com o comando de build/start do seu frontend
